project 'JGHistogramView.xcodeproj'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'JGHistogramView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JGHistogramView

  pod 'FDFullscreenPopGesture', '1.1'
  pod 'Masonry'
  pod 'SDAutoLayout'
  
  
  target 'JGHistogramViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGHistogramViewUITests' do
    # Pods for testing
  end

end
